# Site settings
title: brainchest
email: stephan@brainchest.net
description: > # this means to ignore newlines until "baseurl:"
  brainchest is a small one-man startup for developing apps. I'm doing
  this for fun, learning and building up something personal. Apps are
  released when they are ready without a deadline.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brainchest.net" # the base hostname & protocol for your site
twitter_username: brainchest
github_username:  brainchest

# Build settings
markdown: kramdown
